= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Operational Insights and the SDK.
:page-toclevels: 3
:table-caption!:


[abstract]
{description}



In line with the https://golang.org/doc/devel/release.html#policy[Golang project], {name-sdk} supports both the current, and the previous, versions of Go.
Earlier versions may work, but are not supported.


== Platform Compatibility




=== OS Compatibility

include::{sdk_api}@operational-insights-sdk:shared:partial$compatibility.adoc[tag=os-compat-jvm]





=== Network Requirements

include::{sdk_api}@operational-insights-sdk:shared:partial$network-requirements.adoc[tag=lan-like]



== Operational Insights Compatibility



The 1.0 Operational Insights SDKs are fully compatible with all currently supported releases of Operational Insights.
The 1.0 {name_platform} SDK also supports the poll-based {async-server-api-feature-name} introduced in Operational Insights Enterprise Server 2.2.

////
== Couchbase Analytics Compatibility


The {sdk_dot_minor} {name-sdk} is compatible with our hosted Capella Analytics service, and with recent versions of self-managed Enterprise Analytics.
////


////
*TODO*
table
////


////
=== Capella Analytics Compatibility


Capella Analytics is a fully hosted service, continually updated, and offering the latest version --
with users having a few weeks to upgrade from the previous version.
As such, the latest Couchbase Analytics SDKs are tested against the latest versions.
Where older versions of the {name-sdk} pre-date significant new features in Capella Analytics, those differences will be noted in this section.
////






=== API Version

include::{sdk_api}@operational-insights-sdk:shared:partial$compatibility.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@operational-insights-sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]





////
=== Older Analytics SDK Versions

include::{version-common}@operational-insights-sdk:shared:partial$archive.adoc[tag=link]
////

////
Note the https://www.couchbase.com/support-policy[End of Life dates^] for {name-sdk} versions.
See the notes there for Support details.
////


// Something on Columnar SDKs??
